Netgen\Bundle\EzSocialConnectBundle\Entity\OAuthEz:
    type: entity
    table: ngsocialconnect
    repositoryClass: Netgen\Bundle\EzSocialConnectBundle\Entity\Repository\OAuthEzRepository
    id:
        ezUserId:
            type: integer
            column: ez_user_id
            id: true
        resourceName:
            type: string
            column: resource_name
    fields:
        resourceUserId:
            type: string
            column: resource_user_id
        disconnectable:
            type: boolean
            column: disconnectable
