facebook_login:
    path: /login/login_facebook
    defaults: { _controller: ezpublish.security.controller:loginAction }

google_login:
    path: /login/login_google
    defaults: { _controller: ezpublish.security.controller:loginAction }

twitter_login:
    path: /login/login_twitter
    defaults: { _controller: ezpublish.security.controller:loginAction }

linkedin_login:
    path: /login/login_linkedin
    defaults: { _controller: ezpublish.security.controller:loginAction }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

netgen_social_connect_ez:
    path: /ezconnect/{resourceName}
    defaults: { _controller: netgen.social_connect.controller.connect:connectUser }

netgen_social_disconnect_ez:
    path: /ezdisconnect/{resourceName}
    defaults: { _controller: netgen.social_connect.controller.connect:disconnectUser }

netgen_finish_connecting:
    path: /ezconnect_finish
    defaults: { _controller: netgen.social_connect.controller.connect:finishConnecting }
